### ISSUE TITLE
IANA review

### ISSUE THREAD

**Issue by petervanderstok** [anima-wg/constrained-join-proxy#13]
Thanks for your reaction.
Suggestion for new readable titles are below. I will insert them in the coming version 10 of the draft.

__________________________________________________________________
OLD
   Attribute Value: brski.jp
   Description: This BRSKI resource type is used to query and return the
                supported BRSKI (CoAP over DTLS) port of the constrained
                Join Proxy.
   Reference: [this document]

   Attribute Value: brski.rjp
   Description: This BRSKI resource type is used to query and return the
                supported BRSKI JPY protocol port of the Registrar.
   Reference: [this document]

NEW

   Attribute Value: brski.jp
   Description: This BRSKI resource type is used to query and return the
                supported BRSKI resources of the constrained Join Proxy.
   Reference: [this document]

   Attribute Value: brski.rjp
   Description: This BRSKI resource type is used for the constrained Join Proxy
                to query and return Join Proxy specific BRSKI resources of a Registrar.
   Reference: [this document]

___________________________________________________________
Hope this is understandable enough,

Greetings,

Peter

Sabrina Tanamal via RT schreef op 2022-04-06 00:50:

Dear Authors,

We have a response from the designated expert for Resource Type (rt=) Link Target Attribute Values:

I looked at the registration requests in the draft.
They use somewhat unusual language about discovering ports - resource discovery is understood to discover resources. For brski.jp, this appears to be about discovering a CoAP or CoAPs entry point (without describing how exactly that is then used, e.g., what happens if that has a different IP address in the authority than the request address). For brski.rjp, this appears to be about discovering an entry point for a protocol that I don’t seem to fully understand the description for.

I didn’t try to obtain a deep understanding of the protocol before writing this, but I would prefer if the language used for the description were understandable for other registrants in this registry, i.e., discussing resources, not ports (port numbers?).

All the other criteria for a registration appear to be fulfilled.

====

Best regards,

Sabrina Tanamal
Lead IANA Services Specialist

**Comment by toerless** [comment]
Adding Carsten, who raised the issue during IANA review (no idea if he's subscribed to the github issue).

I actually wouldn't understand the new terminology "resources" better than the old,
more explanatory text. If "resources" is a word that CoAP experts like to see
for terminology consistency, then why not both. Eg.:

Description: This BRSKI resource type is used to query and return the
              supported BRSKI resources (CoAP over DTLS port) of the constrained Join Proxy.

But how avbout letting Carsten suggest text ?

Cheers
    Toerless

**Comment by toerless** [comment]
On 2022-04-07, at 11:50, Toerless Eckert ***@***.***> wrote:
> 
> But how avbout letting Carsten suggest text ?

Maybe you could answer my question first?

(How do the mechanisms defined in this specification make use of the resources returned?)

Removing the clue that somehow this is about extracting port numbers does hide my problem conveniently, but does not address it.

Please do not use mechanisms outside github issues to implicate me in an issue discussion (instead use mentions; I’m @cabo).

Grüße, Carsten

**Comment by cabo** [comment]
(And you can see what I meant with the sentence at the end of the previous issue comment.)

**Comment by toerless** [comment]
Not sure i understand the github magic completely.
I hope that just replying from email with @cabo will bring the reply to your attention.

The join proxy acts as a link-local to IP-path CoAP proxy to forward DTLS messages
for BRSKI enrolment between pledge and registrar. The purpose of this step is to avoid
that a pledge need to first get a non-link-local IP address and therefore have to have a lot more
of IP running, as well as being permitted into the network first. Something which with
BRSKI first requires the enrolment step.

On Thu, Apr 07, 2022 at 11:55:43AM +0200, Carsten Bormann wrote:
> On 2022-04-07, at 11:50, Toerless Eckert ***@***.***> wrote:
> > 
> > But how avbout letting Carsten suggest text ?
> 
> Maybe you could answer my question first?
> 
> (How do the mechanisms defined in this specification make use of the resources returned?)
> 
> Removing the clue that somehow this is about extracting port numbers does hide my problem conveniently, but does not address it.
> 
> Please do not use mechanisms outside github issues to implicate me in an issue discussion (instead use mentions; I’m @cabo).
> 
> Grüße, Carsten

-- 
---
***@***.***

**Comment by toerless** [comment]
Hah. and the @cabo seems to have worked. Learning by being slapped into submission. Nice ;-)

**Comment by cabo** [comment]
OK, that is the mechanism.

Now: How do the mechanisms defined in this specification make use of the resources returned from CoAP discovery?  Please explain the specific steps (not of the discovery, but of how the result is actually used in your protocol).

**Comment by toerless** [comment]
@cabo 

On Thu, Apr 07, 2022 at 03:59:31AM -0700, cabo wrote:
> OK, that is the mechanism.
> Now: How do the mechanisms defined in this specification make use of the resources returned from CoAP discovery?  Please explain the specific steps (not of the discovery, but of how the result is actually used in your protocol).


For example: draft-ietf-anima-constrained-join-proxy 6.1.1

     REQ: GET coap://[IP_address]/.well-known/core?rt=brski.rjp

     RES: 2.05 Content
     <coaps://[IP_address]:join-port>; rt="brski.rjp"

I am actually not quite sure how this works when you do multicast discovery, i guess
the IP_address field would be empty in the request ?

But ultimately, IP_address and join-port learned are used as a UDP endpoint to run constrained
BRSKI-EST across is.

Cheers
    Toerless

> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/anima-wg/constrained-join-proxy/issues/13#issuecomment-1091593109
> You are receiving this because you commented.
> 
> Message ID: ***@***.***>

-- 
---
***@***.***

**Comment by petervanderstok** [comment]
@ cabo

I seem to understand that cabo wants to be sure that the IP address and 
port, returned by the discovery, are used for the following requests to 
either Join Proxy or Registrar.
correct?

Peter
Toerless Eckert schreef op 2022-04-07 14:30:

> @cabo
> 
> On Thu, Apr 07, 2022 at 03:59:31AM -0700, cabo wrote:
>> OK, that is the mechanism.
>> Now: How do the mechanisms defined in this specification make use of 
>> the resources returned from CoAP discovery? Please explain the 
>> specific steps (not of the discovery, but of how the result is 
>> actually used in your protocol).
> 
> For example: draft-ietf-anima-constrained-join-proxy 6.1.1
> 
> REQ: GET coap://[IP_address]/.well-known/core?rt=brski.rjp
> 
> RES: 2.05 Content
> <coaps://[IP_address]:join-port>; rt="brski.rjp"
> 
> I am actually not quite sure how this works when you do multicast 
> discovery, i guess
> the IP_address field would be empty in the request ?
> 
> But ultimately, IP_address and join-port learned are used as a UDP 
> endpoint to run constrained
> BRSKI-EST across is.
> 
> Cheers
> Toerless
> 
>> --
>> Reply to this email directly or view it on GitHub:
>> https://github.com/anima-wg/constrained-join-proxy/issues/13#issuecomment-1091593109
>> You are receiving this because you commented.
>> 
>> Message ID: ***@***.***>
> 
> --
> ---
> ***@***.***
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/anima-wg/constrained-join-proxy/issues/13#issuecomment-1091675811
[2]

**Comment by toerless** [comment]
Peter: writing @ cabo does not result in a hotlink on github, you need to write @cabo to trigger the calling the ghost of cabo to the message.

I have not attempted to question @cabo why he is asking, i am sure once he understands what we're doing well enough he will explain himself as necessary.

**Comment by petervanderstok** [comment]
OK, I will leave things as they are apart from the rephrasing of the 
IANA subjects as I distributed in the reaction to IANA.

Toerless Eckert schreef op 2022-04-07 16:03:

> Peter: writing @ cabo does not result in a hotlink on github, you need 
> to write @cabo [1] to trigger the calling the ghost of cabo to the 
> message.
> 
> I have not attempted to question @cabo [1] why he is asking, i am sure 
> once he understands what we're doing well enough he will explain 
> himself as necessary.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/cabo
[2] 
https://github.com/anima-wg/constrained-join-proxy/issues/13#issuecomment-1091779641
[3]

**Comment by EskoDijk** [comment]
Just seeing the 'NEW' proposed text on top of this issue, and this is not fully correct I think to speak about 'resources' here. I provided earlier comments that lead to the current text, to avoid the term 'resources'.  Since there are no CoAP resources discovered using the brski.jp and brski.rjp types. Only a host (IP address) and port is discovered by using the CoAP mechanism. You can also view it as discovering a root resource that is labeled with a type (rt). An example below from the draft:

  REQ: GET coap://[FF02::FD]/.well-known/core?rt=brski.jp

     RES: 2.05 Content
     <coaps://[IP_address]:join-port>;rt=brski.jp

The semantics of this is not that there is a particular resource hosted at the Join Proxy, but rather that the entire CoAPS endpoint at that port provides access to all standard Constrained-BRSKI resources (like /.well-known/brski/.... ) without doing a detailed specification of what that is. (That is not needed, since they are well-known ... and well-known resources are those not requiring discovery, of course)

If needed the Pledge may connect via DTLS and even send a unicast GET /.well-known/core  to the advertised endpoint, to discover more details about what the Registrar offers in terms of CoAPS resources.

For the resource type 'brski.rjp' we are using the same mechanism although the CoAP purists may find this strange because the discovered endpoint is not a CoAP endpoint but rather a "JPY protocol" over UDP with a specific CBOR based format. Not sure if that's the cause of confusion here (it was a bit for me when I initially reviewed this.)
