### ISSUE TITLE
discovery of Registrar without Join Proxy?

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-join-proxy#27]
The mechanism described in section https://www.ietf.org/archive/id/draft-ietf-anima-constrained-join-proxy-10.html#name-pledge-discovers-registrar is redundant, if the Registrar will just act as a pseudo-join proxy.
Without this, there is only one discovery for the pledge to do.

**Comment by EskoDijk** [comment]
Yes, agree that's better. The Registrar will just offer a join-proxy interface to itself, in this special case. (Normally the Registrar is not in link-local proximity - but it could be.)
