### ISSUE TITLE
how to document discovery mechanisms

### ISSUE THREAD

**Issue by mcr** [anima-wg/constrained-join-proxy#28]
# Pledge Discovery of Join Proxy
1. for pledge discovery of join proxy, we expect to use a LL-multicast discovery mechanism. Either GRASP (in an ACP context), or multicast CoAP discovery.

# Join Proxy Discovery of Registrar
1. for join-proxy discovery of Registrar, in an ACP context, we expect to use GRASP.
2. for networks which support DNS-SD (such as Thread), then unicast queries to the DNS-SD server SHOULD be used
3. for join-proxy discovery of Registrar, outside of an ACP context, for some mesh-under networks (WiFi extenders, and ???), then multicast CoAP discovery can be used.
4. for networks which are route-over, but which do **not** support **multicast** (such as 6tisch), then multicast CoAP discovery can not be done (due lack of multicast), and that network needs to define it's own way for the join proxy to discovery the Registrar.

This text should go into constrained-voucher document.
Text that explains what are the *stateless* aspects for GRASP, multicast-CoAP and DNS-SD needs to go into the  constrained-join-proxy document.

**Comment by mcr** [comment]
Rename first part to make it less about Join Proxy, call it maybe "Registrar Interface"

**Comment by EskoDijk** [comment]
If we follow RFC 8995, for GRASP it defines discovery of a node that advertises the "AN_Proxy" objective. And it explains this may be the Registrar or an actual Proxy; and the Pledge wouldn't know. Seems we can follow same terminology in Constrained BRSKI? So in this light "Join Proxy" seems close enough.

So how we could then distribute the content:
* Pledge's discovery of AN_Proxy / Join Proxy -> include in Constrained-BRSKI.   
    *  For those people who don't want an actual proxy in their system: they can implement a Registrar that implements the AN_Proxy interface itself. 
    * E.g. because it only operates in a mesh-under type network or a star topology.
* Implementation of Join Proxy -> keep as is in the Constrained Join Proxy draft.
    *  This draft is then an "optional read" only for those people who want to implement an actual join proxy. 
    * E.g. because it needs to operate in a mesh network.
    * Defines the new "JPY" protocol which is DTLS-record carried in CBOR envelope.
    * Defines discovery of the Registrar's JPY host/port.
