### ISSUE TITLE
Fig.6: fix little copy/paste issue

### ISSUE THREAD

**Issue by viktorTarasov** [anima-wg/constrained-join-proxy#35]
There is a copy/paste issue of encoded _M_FLOOD_ announcement presented by Fig.6 (square brackets and commas).

And it should be rather like this:
>[M_FLOOD, 51840231, h'fda379a6f6ee00000200000064000001', 180000,
        [
                ["AN_join_registrar", 4, 255, ""],
                [O_IPv6_LOCATOR, h'fda379a6f6ee00000200000064000001', IPPROTO_TCP, 8443]
        ],
        [
                ["AN_join_registrar", 4, 255, "BRSKI_JP"],
                [O_IPv6_LOCATOR, h'fda379a6f6ee00000200000064000001', IPPROTO_UDP, 5684]
        ],
        [
                ["AN_join_registrar", 4, 255, "BRSKI_RJP"],
                [O_IPv6_LOCATOR, h'fda379a6f6ee00000200000064000001', IPPROTO_UDP, 5685]
        ]
]

**Comment by mcr** [comment]
closed by aefee72
