### ISSUE TITLE
new protocol

### ISSUE THREAD

**Issue by petervanderstok** [anima-wg/constrained-join-proxy#4]
So it looks like this message type is a newly defined protocol format over UDP, not a CoAP message as I initially expected. It should be stated explicitly that this is a new protocol ; also e.g. this draft could register a new protocol into IANA "Service Name and Transport Protocol Port Number Registry" with a name and without a default port number (there are many registered protocols there that do this). The service name can make the service and its port discoverable through any IETF defined means like DNS-SD, mDNS.  CoAP discovery doesn't seem useful here because the new-protocol isn't CoAP.
 
For WG discussion: why isn't CoAP re-used to transport this CBOR payload to the Registrar without having to define a new protocol?
(One answer could be that using CoAP will add much more bytes as overhead, e.g. to encode a URI path. And the URI path of the Registrar's "join-proxy resource" would have to be discovered also, not just the port. )
Or, do I have it wrong and was CoAP intended after all?

The way it is currently defined it *is* a new protocol; it is not CoAP-over-DTLS-over-UDP (coaps://) anymore but CoAP-over-DTLS-over-CBORarray-over-UDP. Whether we like it or not ...
An alternative is to encapsulate it in coap:// , so you get CoAP-over-DTLS-over-CoAP-over-UDP which is standard coap (can use standard UDP port 5683 also) so doesn't need any definition as a new protocol over UDP. But this adds much more bytes of overhead; by the way this is the approach used by Thread 1.2.  In this case both the Pledge and the Registrar have to limit the size of their DTLS records such that the 1280 byte limit is not exceeded for the coap:// relay message, for IPv6 over 6lowpan networks.

**Comment by mcr** [comment]
We have DTLS(CoAP(BRSKI)), and the stateless version of this is WRAP(X,DTLS(CoAP(BRSKI))).
I agree that maybe WRAP could have been CoAP.  
WRAP is CBOR encoded.  I agree that things could have been CoAP rather than CBOR.

**Comment by petervanderstok** [comment]
This seems to be closed with addition of text in 9.1
