### ISSUE TITLE
coap port discovery 

### ISSUE THREAD

**Issue by petervanderstok** [anima-wg/constrained-join-proxy#6]
One issue is that the JPY protocol being discovered is not CoAP (see section 5.3 comments), and now we discover it as if it were a CoAP resource.  That seems strange but at the same time re-using CoAP discovery for this is great and avoids having to do other discovery means again which the constrained Join Proxy device would likely not implement or would not be practical.
 
Maybe we could poll the CoRE WG for this idea of CoAP discovery of non-CoAP protocols! 
(In our case, the JPY protocol wraps CoAP-over-DTLS so you can argue that it is a sort of CoAP after all.)

**Comment by mcr** [comment]
I agree.  Let's ask.   It seems fine to discover COAPS resources on the JPY.
It seems weird to discover COAPS-over-UDP-thing though.

**Comment by petervanderstok** [comment]
coaps_over_udp will not be specified, and discovery of coap resources remains in
